version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myfunction
    ports:
      - 8080:8080
    #ホストマシンのlocalhostをdocker側に登録
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db-store: